import datetime


holidays = ["26-Jan-23","07-Mar-23","30-Mar-23","04-Apr-23","07-Apr-23","14-Apr-23","01-May-23","29-Jun-23","15-Aug-23","19-Sep-23","02-Oct-23","24-Oct-23","12-Nov-23","14-Nov-23","27-Nov-23","25-Dec-23"]
holidays_ddmmmyyyy = [datetime.datetime.strptime(each,"%d-%b-%y").strftime("%d%b%Y").upper() for each in holidays]



# WORKING ON DATE FORMATS FROM CSV STRING NAMES IN NSE
avoid_series = ['GS','IV', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'NA', 'NB', 'NC', 'ND', 'NE', 'NF', 'NG',
                'NH', 'NI', 'NJ', 'NK', 'NL', 'NM', 'NN', 'NO', 'NP', 'NQ', 'NR', 'NS', 'NT', 'NU', 'NV', 'NW', 'NX', 'NY', 'P2', 'W1',
                'W3', 'Y1', 'Y2', 'Y3','Y5','Y6', 'Y7','Y8', 'YA', 'YC', 'YG', 'YH', 'YI','YJ', 'YK', 'YL', 'YN', 'YO', 'YP', 'YR', 'YS', 'YT', 'YU', 'YV', 'YW', 'YY', 'YZ',
                'Z2', 'Z3', 'Z4', 'Z7', 'Z8', 'ZA', 'ZH', 'ZJ', 'ZK',
                ' GS',' IV', ' N1', ' N2', ' N3', ' N4', ' N5', ' N6', ' N7', ' N8', ' N9', ' NA', ' NB', ' NC', ' ND', ' NE', ' NF', ' NG',
                ' NH', ' NI', ' NJ', ' NK', ' NL', ' NM', ' NN', ' NO', ' NP', ' NQ', ' NR', ' NS', ' NT', ' NU', ' NV', ' NW', ' NX', ' NY', ' P2', ' W1',
                ' W3', ' Y1', ' Y2', ' Y3',' Y5',' Y6', ' Y7',' Y8', ' YA', ' YC', ' YG', ' YH', ' YI',' YJ', ' YK', ' YL', ' YM', ' YN', ' YO', ' YP', ' YR', ' YS', ' YT', ' YU', ' YV', ' YW', ' YY', ' YZ',
                ' Z2', ' Z3', ' Z4', ' Z7', ' Z8', ' ZA', ' ZH', ' ZJ', ' ZK','YX', ' Z5', ' Z9', ' Z5', ' ZI',' MF',' GB',
                ]


avoid_bse_series = ['F ', 'G ']
# avoid_bse_stocks USED cos these stocks are available in NSE as well
avoid_bse_stocks = ['21ST CEN.MGM','3I INFOTECH ','3M INDIA LTD','AADI INDUS L','AAREY DRUGS ','AARTI DRUGS ','AARTI INDUST',
                    'AARVEE DENIM', 'ABAN OFFSHO ', 'ABB LTD.    ','ABBOTT (I)  ','ABFRL       ','ACC LTD     ','ACRYCIL LTD.','ACTION CONST',
                    'ADANI PORTS ','ADANI POWER ','ADF FOODS LT','ADORWELDING ','ADVANI HOTEL','AEGIS LOGIS ','AGAR IND COR','AGRI TECH   ','AHLUWALIA CO',
                    'AIAENGINEER ','AJANTA PHARM','AKSHAR      ','AKSHARCHEM I','ALBERT DAVID','ALEMBIC LTD.','ALKYL AMINES','ALLSEC TECH ','ALMONDZ GLO ',
                    'ALOK INDS.  ','ALPA LAB    ','ALPHAGEO (I)','ALPS INDS.  ','AMAR RAJA BA','AMBICA AGAR.','AMBIKA COTTO','AMBUJA CEME ','AMD INDUS   ',
                    'ANDHRA CEMEN','ANDHRA SUGAR','ANDREW YULE ','ANIK INDS   ','ANKIT METAL ','APAR INDUS. ','APCOTEX IND ','APL APOLLO  ','APOLLO HOSP.','APOLLOPIPES ',
                    'APOLLO TYRES','APTECH LTD  ','ARCHIES LTD ','ARCHIDPLY IN','ARIES AGRO  ','ARIHANT CAP.','ARIH SUPER  ','ARMAN FIN   ','ARO GRANITE ','ARSS INFRA  ',
                    'ARROWGREEN  ','ARSHIYA     ','ARVIND Ltd  ','ARVINDFASN  ','ARVSMART    ','ASAHI IN.GLA','ASAHI SONG  ','ASHIANA HOU ','ASHIMA LTD. ', 'ASHOK LEYL. ',
                    'ASHOKA      ', 'ASIAN HTL E ','ASIAN PAINTS', 'ASIANENE    ', 'ASIANHOTNR  ', 'ASTEC LIFE  ','ASTERDM     ', 'ASTRAL      ','ASTRA MICRO ', 'ASTRAZEN.PH.',
                    'ATUL AUTO   ','ATUL LTD.   ','AUBANK      ','AURIONPRO SO','AUROB.PHARMA','AURUM       ','AURUMPP     ','AUSOM ENT   ',
                    'AVANTI FEEDS','AVT NATURAL ',
                    '20 MICRONS  ','3PLAND      ','5PAISA      ','63MOONS     ','A2ZINFRA    ','AAATECH     ','AAREY DRUGS ','AARTI DRUGS ','AARTISURF   ','AAVAS       ',
                    'ABCAPITAL   ','ABFRL       ','ABSLAMC     ','ABSLBANETF  ','ABSLNN50ET  ','ACCELYA     ','ACI         ','ADANI PORTS ','ADANI POWER ','ADANIGREEN  ',
                    'ADANITRANS  ','ADROITINFO  ','ADVENZYMES  ','AETHER      ','AFFLE       ','AGI         ','AGRI TECH   ','AGSTRA      ','AIRTELPP    ','AJMERA      ',
                    'AKSHAR      ','AKZOINDIA   ','ALANKIT     ','ALICON      ','ALKALI      ','ALKEM       ','ALLCARGO    ','AMBER       ','AMIORG      ','AMJLAND     ',
                    'AMRUTANJAN  ','ANANDRATHI  ','ANANTRAJ    ','ANGELONE    ','ANIK INDS   ','ANKIT METAL ','ANMOL       ','ANUP        ','ANURAS      ','APCOTEX IND ',
                    'APEX        ','APL APOLLO  ','APOLLO      ','APTUS       ','ARMAN FIN   ','ARO GRANITE ','ARROWGREEN  ','ARSHIYA     ','ARTEMISMED  ','ARVINDFASN  ',
                    'ARVSMART    ','ASAHI SONG  ','ASHOKA      ','ASIANENE    ','ASIANHOTNR  ','ASTERDM     ','ASTRA MICRO ','ASTRAL      ','ASTRON      ','ATGL        ',
                    'ATLANTA     ','ATUL AUTO   ','AUBANK      ','AURUM       ','AURUMPP     ','AUSOM ENT   ','AUTO AXLES  ','AUTOIND     ','AVADHSUGAR  ','AVROIND     ',
                    'AWHCL       ','AWL         ','AXIS BANK   ','AXISCADES   ','AXISCETF    ','AXISGOLD    ','AXISTECETF  ','AXITA       ','AYMSYNTEX   ','BAJAJ AUTO  ',
                    'BAJAJCON    ','BAJAJ ELECT.','BALAJI AMINE','BALAJI TELE.','BALKRISH IND','BALARPUR IND','BALMER LAWRI','BALRAM.CHINI','BANARAS BEAD','BANSW.SYNTEX',
                    'BASF INDIA  ','BCLIL       ','BCP LTD     ','BEDMUTHA IN ','BF UTILI    ','BHAGIRA.CHEM','BHAGIL      ','BHAGYA INL  ','BHANDARI HOS','BHARAT FORGE',
                    'BHARAT GEARS','BHARAT RA(PS','BIOCON LTD. ','BIRLA CORPN.','BIRLATYRES  ','BLB LTD.    ','BLISSGVS PH ','BLUE DART EX','BLUE STAR   ','BRITANIA IND',
                    'BROOKS LABS ',
                    'BAJAJHCARE  ','BAJAJHIND   ','BAJFINANCE  ','BAL PHARMA  ','BALKRISHNA  ','BANDHANBNK  ','BANG        ','BANKBARODA  ','BANKBEES    ','BARBEQUE    ',
                    'BATA INDIA  ','BAYER CROP  ','BBOX        ','BBTCL       ','BCG         ','BCONCEPTS   ','BDL         ','BEARDSELL   ','BECTORFOOD  ','BERGE PAINT ',
                    'BESTAGRO    ','BF INVEST   ','BGR ENERGY  ','BHARATWIRE  ','BHARTI ARTL ','BHEL        ','BIGBLOC     ','BIKAJI      ','BINDALAGRO  ','BIOFIL CHEM ',
                    'BIRET       ','BIRLACABLE  ','BKMINDST    ','BL KASHYAP  ','BLS         ','BODAL CHEM  ','BOM DYEING  ','BOROLTD     ','BORORENEW   ','BOSCH LTD   ',
                    'BRIGADE     ','BRNL        ','BSLGOLDETF  ','BSLNIFTY    ','BSLSENETFG  ','BSOFT       ','BTML        ','BURNPUR     ','CAMLINFINE  ','CAMPUS      ',
                    'CALIFORN.SOF','CANARA BANK ','CANFIN HOMES','CAPLIN POINT','CAPITAL TRUS','','CASTROL     ','CCL PRODUCTS','CEAT LIMITED','CELEBRITYFAS','CENTRUM CAP ',
                    'CENTUM ELEC ','CENTURY TEXT','CERA SANITAR','CEREBRA INTE','CESC LTD.   ','CHAMBAL FERT','CHEMBOND CHM','CHEMFABALKA ','CHENNAI PET.','CHEVIOT CO. ','CHOICE INT. ',
                    'CIGNITI TECH','CIPLA LTD.  ','CMI LTD.    ','COLGATE PALM','COMPUAGE INF','COMPUCOM SOF','CONTAIN.CORP','CONFI PETRO ','CONTROL PRNT','CORAL (I)FIN',
                    'COROM INTER ','COUNTRY COND','CRISIL LTD  ','CUBEX TUBING','CUMMINS (I) ','CUPID LTD   ',
                    'CAMS        ','CANTABIL    ','CAPACITE    ','CAREERP     ','CARERATING  ','CARTRADE    ','CARYSIL     ','CCHHL       ','CENTRAL BK  ','CENTURYPLY  ',
                    'CGCL        ','CGPOWER     ','CHALET      ','CHEMCON     ','CHEMPLASTS  ','CHOLAFIN    ','CHOLAHLDNG  ','CINELINE    ','CINEVISTA   ','CLEAN       ',
                    'CLEDUCATE   ','CMSINFO     ','COAL INDIA  ','COAST CORP  ','COCHINSHIP  ','COFFEEDAY   ','COFORGE     ','CORDS CABLE ','COSMOFIRST  ','CPSE ETF    ',
                    'CRAFTSMAN   ','CREATIVE    ','CREDITACC   ','CREST       ','CROMPTON    ','CSBBANK     ','CSLFINANCE  ','CYBER MEDIA ','CYBERTECH   ','CYIENT      ',
                    'DABUR (I)   ','DAMOINDUS   ','DATAM GLOB  ','DCM FINANCIA','DCW LTD.    ','DECAN CEMENT','DEEPAK FERT.','DEEPAK NITR.','DEEPIND     ','DEN NETWORK ',
                    'DHAMPUR SUGA','DHANALAK.BNK','DHARANI SUG ','DIC INDIA   ','DIVI\'S LAB. ', 'DIGISPICE   ','DIXON       ', 'DLF LIMITED ', 'DLINK IND   ','DMART       ',
                    'DMCC        ','DONEAR IND. ','DR.REDDY\'S  ','DREDGING COR','DWAR SUGAR  ','DYNEMIC PRO ',
                    'D B CORP    ','D B REALTY  ','DAAWAT      ','DALBHARAT   ','DALMIASUG   ','DATAPATTNS  ','DBL         ','DBOL        ','DCAL        ','DCBBANK     ',
                    'DCI         ','DCMNVL      ','DCMSHRIRAM  ','DCXINDIA    ','DE NORA     ','DEEPENR     ','DELHIVERY   ','DELPHIFX    ','DELTA CORP  ','DELTAMAGNT  ',
                    'DEVIT       ','DEVYANI     ','DFM FOODS   ','DGCONTENT   ','DHANI       ','DHRUV       ','DHUNINV     ','DIAMONDYD   ','DIGISPICE   ','DISH TV     ',
                    'DIXON       ','DMART       ','DMCC        ','DNAMEDIA    ','DODLA       ','DOLATALGO   ','DOLLAR      ','DRCSYSTEMS  ','DREAMFOLKS  ','DRL         ',
                    'DSPN50ETF   ','DSPNEWETF   ','DSPQ50ETF   ','DSPSILVETF  ','DUCON       ','DVL         ','DYNAMIC     ',

                    'E.I.D.PAR   ','EASTER SI(PS','EDUCOMP SOLN','EICHER MOTOR','EIH ASSO.HOT','EIH LTD.    ','EIMCO ELECON','ELEC.CASTING','ELECON ENG  ',
                    'ELECTROTHERM','EMAMI LTD.  ','EMAMI PAPER ','EMKAY GLOB F','ENERGY DEV. ','ENGINRS.(I) ','ESSAR SHIP  ','ESTER INDUS.','EVEREADY (I)',
                    'EVEREADY (I)','EXCEL INDUST','EXIDE IND.  ','EASEMYTRIP  ','ECLERX      ','EDELWEISS   ',
                    'ELGI EQUIP  ','EMAMIREAL   ','EMBASSY     ','EMIL        ','EMMBI       ','EMUDHRA     ','ENDURANCE   ','EPL         ','EQUIPPP     ','EQUITASBNK  ',
                    'ERIS        ','EROS MEDIA  ','ESAB INDIA  ','ESCORTS     ','ETHOSLTD    ','EXCEL       ','EXPLEOSOL   ','EXXARO      ',
                    'FCS SOFTWARE','FDC LIMITED ','FEDERAL BANK','FIBERWB IN  ','FIEM INDS   ','FINOL. CABLE','FINOLEX IND.','FED MOG GOE ','FOODS & INNS','FORCE MOTR  ',
                    'FAIRCHEMOR  ','FCONSUMER   ','FSL         ','FUSION      ',
                    'FEL         ','FELDVR      ','FINEORG     ','FINOPB      ','FIVESTAR    ','FLEXITUFF   ','FLUOROCHEM  ','FMNL        ','FORTIS      ','FSC         ',
                    'GAIL (I) LTD','GUJ AMB EXP ','G.M.BREWERI ','GABRIEL(I)  ','GANDHI SP.TU','GANESH ECOSP','GANESH HSG. ','GANGESSEC   ','GATI LTD.   ',
                    'GAYATRI PROJ','GENESYS INT.','GHCL LTD    ','GIC HOUSING ','GILLETTE (I)','GLAXOSMITH  ','GLENMARK PHA','GMM PFAUDLER','GODFREY PH  ',
                    'GODREJ CONS ','GOENKA DIAM ','GOKALDAS    ','GOLDEN TOB  ','GOLDIAM INT.','GOODYEAR (I)','GRANULES (I)','GRAPHITE IN.','GRASIM IND. ',
                    'GRAUER& WEIL','GREAT EASTE ','GREAVES COTT','GREENPLY IND','GRIND NORTON','GRM OVERSEAS','GRNLAM IND  ','GTL LTD.    ','GUFIC BIO SC',
                    'GUJ APOIND  ','GUJ.ALKALI  ','GUJ.MINERAL ','GUJ.NARMADA ','GUJ.RAFFIA  ','GUJ.ST.FERT ','GUJGAS      ','GULSHAN POLY','GVK POWERINF',
                    'GALAXYSURF  ','GALLANTT    ','GARFIBRES   ','GATEWAY     ','GAYAHWS     ','GEECEE      ','GENCON      ','GENUS POWER ',
                    'GENUSPAPER  ','GEOJITFSL   ','GEPIL       ','GET&D       ','GFLLIMITED  ','GICRE       ','GLAND       ','GLOBAL VECT ','GLOBUS SPR  ','GLS         ',
                    'GMRINFRA    ','GMRP&UI     ','GNA         ','GOA CARBON  ','GOCLCORP    ','GOCOLORS    ','GODREJ IND  ','GODREJ PROP ','GODREJAGRO  ','GOKULAGRO   ',
                    'GOLDBEES    ','GOODLUCK    ','GOYALALUM   ','GPPL        ','GPT INFRA   ','GRAVITA     ','GREENPANEL  ','GREENPOWER  ','GRINFRA     ','GRPLTD      ',
                    'GRSE        ','GRWRHITECH  ','GSTL        ','GTPL        ','GULFOIL LUB ','GULFPETRO   ',




                    'HAL         ','HAPPSTMNDS  ','HARDWYN     ','HARIOMPIPE  ',
                    'HARSHA      ','HAVISHA     ','HBANKETF    ','HCG         ','HDFC        ','HDFC BANK   ','HDFCAMC     ','HDFCGROWTH  ','HDFCLIFE    ','HDFCLOWVOL  ',
                    'HDFCMFGETF  ','HDFCMOMENT  ','HDFCNEXT50  ','HDFCNIF100  ','HDFCNIFETF  ','HDFCNIFIT   ','HDFCPVTBAN  ','HDFCSILVER  ','HDFCVALUE   ','HEADSUP     ',
                    'HEALTHY     ','HEMIPROP    ','HERANBA     ','HERITGFOOD  ','HEROMOTOCO  ','HEXATRADEX  ','HFCL        ','HGINFRA     ','HIL         ','HINDALCO    ',
                    'HINDWAREAP  ','HITECH      ','HITECHCORP  ','HITECHGEAR  ','HLEGLAS     ','HLVLTD      ','HMVL        ','HNGSNGBEES  ','HOMEFIRST   ','HONDAPOWER  ',
                    'HPAL        ','HPIL        ','HPL         ','HSCL        ','HT MEDIA    ','HUBTOWN     ','HUDCO       ','HUHTAMAKI   ','IBUL HSG FIN','ICICI BANK  ',
                    'ICICI500    ','ICICIALPLV  ','ICICIAUTO   ','ICICIB22    ','ICICIBANKN  ','ICICIBANKP  ','ICICICONSU  ','ICICIFIN    ','ICICIFMCG   ','ICICIGI     ',
                    'ICICIGOLD   ','ICICIINFRA  ','ICICILOVOL  ','ICICIM150   ','ICICIMCAP   ','ICICIMOM30  ','ICICINF100  ','ICICINIFTY  ','ICICINV20   ','ICICINXT50  ',
                    'ICICIPHARM  ','ICICIPRULI  ','ICICISENSX  ','ICICITECH   ','ICRA        ','IDBIGOLD    ','IDEA        ','IDFC        ','IDFCFIRSTB  ',
                    'IEX         ','IFB AGRO    ','IFGLEXPOR   ','IIFL        ','IIFLSEC     ','IL&FS TRANS ','IMAGICAA    ','INCREDIBLE  ','IND TERRAIN ','INDIAMART   ',
                    'INDIGO      ','INDIGOPNTS  ','INDO RAMA   ','INDO THAI   ','INDOSTAR    ','INDUSTOWER  ','INFIBEAM    ','INFOBEAN    ','INFOMEDIA   ','INFRABEES   ',
                    'INNOVATIVE  ','INOXGREEN   ','INOXWIND    ','INSPIRISYS  ','INTELLECT   ','INTENS TECH ','INVENTURE   ','IPL         ','IRCON       ','IRCTC       ','IRFC        ',
                    'IRIS        ','ISEC        ','ISGEC       ','ISMT LTD    ','ITDCEM      ','IVZINGOLD   ','IWEL        ','IZMO        ','J & K BANK  ','JAI CORP LTD',
                    'JAMNA AUTO  ','JAY NECO IND','JCHAC       ','JETAIRWAYS  ','JETFREIGHT  ','JINDAL SAW  ','JITFINFRA   ','JK CEMENT   ','JK LAKSHMI  ','JK PAPER    ',
                    'JPPOWER     ','JSL         ','JSW ENERGY  ','JSWHL       ','JSWISPL     ','JTEKTINDIA  ','JTLIND      ','JUBL FOOD   ','JUBLINGREA  ','JUBLPHARMA  ',
                    'JUNIORBEES  ','JUSTDIAL    ','JWL         ','JYOTHYLAB   ','','KALYANKJIL  ','KAMDHENU    ','KANANI IND  ','KAYA        ','KAYNES      ','KBCGLOBAL   ',
                    'KEEPLEARN   ','KELLTONTEC  ','KESORAM IND ','KHADIM      ','KIMS        ','KINGFA      ','KIOCL       ','KOKUYOCMLN  ','KOLTEPATIL  ','KORE        ',
                    'KOTAK PSU BK','KOTAKBKETF  ','KOTAKNIFTY  ','KPIGREEN    ','KPITTECH    ','KRSNAA      ','KSB         ','KSOLVES     ','KUANTUM     ','LALPATHLAB  ',
                    'LANCER      ','LASA        ','LATENTVIEW  ','LAURUSLABS  ','LAXMIMACH   ','LEMONTREE   ','LGB FORGE   ','LICI        ','LICNETFN50  ','LICNETFSEN  ',
                    'LICNFNHGP   ','LIKHITHA    ','LINC        ','LINDEINDIA  ','LODHA       ','LOKESH MACH ','LOVABLE     ','LTTS        ','LUMAX IND   ','LUMAX TECH  ',
                    'LUXIND      ','LXCHEM      ','LYKA LABS   ','LYPSA GEMS  ','MAANALU     ','MADRASFERT  ','MAESGETF    ','MAFANG      ','MAFSETF     ','MAHA STEEL  ',
                    'MAHEPC      ','MAHINDCIE   ','MAHKTECH    ','MAHLOG      ','MAITHAN ALL ','MALLCOM     ','MALU PAPER  ','MAM150ETF   ','MAMFGETF    ','MAN INFRA   ',
                    'MAN50ETF    ','MANORAMA    ','MANORG      ','MANYAVAR    ','MAPMYINDIA  ','MARKSANS    ','MASFIN      ','MASPTOP50   ','MATRIMONY   ','MAXHEALTH   ',
                    'MAXVIL      ','MAZDOCK     ','MBLINFRA    ','MEDANTA     ','MEDICO      ','MEDPLUS     ','MEGASTAR    ','MEP         ','METALFORGE  ','METROBRAND  ',
                    'METROPOLIS  ','MFL         ','MFSL        ','MGL         ','MIDHANI     ','MINDACORP   ','MINDSPACE   ','MODISONLTD  ','MOHEALTH    ','MOL         ',
                    'MOLOWVOL    ','MOM100      ','MOM50       ','MOMENTUM    ','MOMOMENTUM  ','MON100      ','MONARCH     ','MONQ50      ','MONTECARLO  ','MOTHERSON   ',
                    'MOTILALOFS  ','MPS LTD     ','MRO-TEK     ','MRPL        ','MSUMI       ','MT EDUCARE  ','MTARTECH    ','MUKTA ARTS  ','MUTHOOT CAP ','MUTHOOT FIN ',
                    'NACLIND     ','NAHAR CAP   ','NAHAR POLY  ','NAM-INDIA   ','NARMADA     ','NATCO PHARM ','NATH BIOGEN ','NAVA        ','NAVKARCORP  ','NAVNETEDUL  ',
                    'NAZARA      ','NBCC        ','NCC         ','NDL         ','NDRAUTO     ','NDTV        ','NECC LTD    ','NELCAST     ','NEOGEN      ','NEWGEN      ',
                    'NGIL        ','NH          ','NHPC        ','NIACL       ','NIF100BEES  ','NIFTYBEES   ','NIFTYQLITY  ','NILASPACES  ','NIPPOBATRY  ','NLCINDIA    ',
                    'NURECA      ','NUVOCO      ','NXTDIGITAL  ','NYKAA       ','OAL         ','OBCL        ','OLECTRA     ','OMINFRAL    ','ONELIFE CAP ','ONMOBILE    ',
                    'OPTIEMUS    ','ORICON ENT  ','ORIENT CEM  ','ORIENTBELL  ','ORIENTELEC  ','ORISSA MINE ','PAISALO     ','PANACHE     ','PARADEEP    ','PARAGMILK   ',
                    'PARAS       ','PARSVNATH   ','PAT INT LOG ','PATANJALI   ','PAYTM       ','PC JEWELLER ','PCBL        ','PDMJEPAPER  ','PDSL        ','PEL         ',
                    'PERSISTENT  ','PGHL        ','PGIL        ','PILANIINVS  ','PILITA      ','PIONEER EMB ','PITTIENG    ','PIX TRANS   ','PNB GILTS   ','PNBHOUSING  ',
                    'PNCINFRA    ','POLICYBZR   ','POLYCAB     ','POLYPLEX    ','POONAWALLA  ','POWER GRID  ','POWERINDIA  ','POWERMECH   ','PPAP        ','PPL         ',
                    'PPLPHARMA   ','PRAKASHSTL  ','PRAXIS      ','PRECAM      ','PRESSMN     ','PRESTIGE    ','PRICOLLTD   ','PRINCEPIPE  ','PRITIKAUTO  ','PRIVISCL    ',
                    'PROZONINTU  ','PRSMJOHNSN  ','PRUDENT     ','PSPPROJECT  ','PSUBNKBEES  ','QNIFTY      ','QUESS       ','QUICKHEAL   ','RADHIKAJWE  ','RADIOCITY   ',
                    'RAILTEL     ','RAIN        ','RAINBOW     ','RAMANEWS    ','RAMASTEEL   ','RAMCOCEM    ','RANE HOLDIN ','RATEGAIN    ','RAYMOND     ','RBA         ',
                    'RBLBANK     ','RECLTD      ','REDINGTON   ','REFEX       ','REL INFRA   ','RELIANCE    ','REPCO HOME  ','RESPON IND  ','RGL         ','RHIM        ',
                    'RICO AUTO   ','RITCO       ','RITES       ','RNAVAL      ','ROLEXRINGS  ','ROSSARI     ','ROSSELL IND ','ROUTE       ','RPOWER      ','RPP INFRA   ',
                    'RPSGVENT    ','RTNINDIA    ','RTNPOWER    ','RUBY MILLS  ','RUSTOMJEE   ','RVHL        ','RVNL        ','SADBHIN     ','SALASAR     ','SALSTEEL    ',
                    'SALZER ELEC ','SANDHAR     ','SANOFI      ','SANSERA     ','SANWARIA    ','SAPPHIRE    ','SARVESHWAR  ','SASKEN      ','SASTASUNDR  ','SAT IND LTD ',
                    'SATIA       ','SATIN       ','SBC         ','SBICARD     ','SBILIFE     ','SCAPDVR     ','SCHAEFFLER  ','SCHAND      ','SCHNEIDER   ','SCPL        ',
                    'SEAMEC LTD  ','SECURCRED   ','SECURKLOUD  ','SEPC        ','SEPOWER     ','SEQUENT     ','SETFNIF50   ','SETFNIFBK   ','SETUINFRA   ','SFL         ',
                    'SGIL        ','SHAH ALLOYS ','SHALBY      ','SHANKARA    ','SHARDACROP  ','SHARIABEES  ','SHEMAROO    ','SHIVALIK    ','SHIVAM AUTO ','SHIVAMILLS  ',
                    'SHK         ','SHREE RAMA  ','SHREEPUSHK  ','SHRIRAMPPS  ','SHYAMMETL   ','SIGACHI     ','SILVER      ','SILVERTUC   ','SIMBHALS    ','SIRCA       ',
                    'SIS         ','SITINET     ','SJS         ','SJVN        ','SKF INDIA   ','SKIPPER     ','SKM EGG PROD','SMARTLINK   ','SMCGLOBAL   ','SMLISUZU    ',
                    'SMLT        ','SMSLIFE     ','SNOWMAN     ','SOBHA       ','SOFTTECH    ','SOLARA      ','SOMI CONVEY ','SONACOMS    ','SOTL        ','SPAL        ',
                    'SPANDANA    ','SPMLINFRA   ','SPORTKING   ','STAR        ','STAR PAPER  ','STARCEMENT  ','STARHEALTH  ','STARTECK    ','STC INDIA   ','STD.INDUST. ','STEL        ',
                    'STERL.TOOLS ','STOVEKRAFT  ','SUMICHEM    ','SUPER HOUSE ','SUPRIYA     ','SURANASOL   ','SURYODAY    ','SUVENPHAR   ','SUVIDHAA    ','SVPGLOB     ','SWSOLAR     ',
                    'SYMPHONY    ','SYNGENE     ','SYRMA       ','TANLA       ','TANTIA CONS ','TARC        ','TARMAT      ','TARSONS     ','TASTY BITE  ','TATA COFFEE ',
                    'TATA COMM   ','TATA ELXSI  ','TATA MOTORS ','TATA POWER  ','TATA STEEL  ','TATACONSUM  ','TATASTLLP   ','TATVA       ','TCIEXP      ','TCNSBRANDS  ',
                    'TCPL PACK   ','TEAMLEASE   ','TECH        ','TECHIN      ','TECHNOE     ','TEGA        ','TEJASNET    ','TEXINFRA    ','TEXMO PIPES ','TGBHOTELS   ',
                    'THEINVEST   ','THERMAX     ','THOMAS COOK ','THYROCARE   ','TIINDIA     ','TIME TECHNO ','TINPLATE    ','TIPSFILMS   ','TITAN       ','TMB         ',
                    'TOKYO PLAST ','TORNT POWER ','TRACXN      ','TREE HOUSE  ','TREJHARA    ','TRIDENT     ','TRIL        ','TRU         ','TV TODAY    ','TV18BRDCST  ',
                    'TVVISION    ','UCAL FUEL   ','UCOBANK     ','UFO         ','UGAR SUGAR  ','UGROCAP     ','UJAAS       ','UJJIVAN     ','UJJIVANSFB  ','UMAEXPORTS  ',
                    'UNICHEM LAB ','UNIVPHOTO   ','UNOMINDA    ','UPL         ','UTIAMC      ','UTIBANKETF  ','UTINEXT50   ','UTINIFTETF  ','UTISENSETF  ','UTISXN50    ',
                    'UTTAM SUGAR ','V2RETAIL    ','VADILAL IND ','VAIBHAVGBL  ','VAKRANGEE   ','VALIANTORG  ','VARROC      ','VBL         ','VEDL        ','VENUSPIPES  ',
                    'VERANDA     ','VETO        ','VIDHIING    ','VIJAYA      ','VIKAS WSP   ','VIKASECO    ','VIKASLIFE   ','VIMTA LABS  ','VINEETLAB   ','VINNY       ',
                    'VIPCLOTHNG  ','VIPUL LTD   ','VISA STEEL  ','VISHAL      ','VISHWARAJ   ','VLS FINANCE ','VMART       ','VRLLOG      ','VSSL        ','VST TILLERS ',
                    'WATERBASE   ','WEBELSOLAR  ','WELCORP     ','WELENT      ','WESTLIFE    ','WEWIN       ','WHIRLPOOL   ','WINDLAS     ','WINPRO      ','WONDERLA    ',
                    'XCHANGING   ','XELPMOC     ','YAARI       ','YES BANK    ','ZEE LEARN   ','ZEEMEDIA    ','ZENITHSTL   ','ZFCVINDIA   ','ZIMLAB      ','ZODIAC      ',
                    'ZOMATO      ','ZUARIIND    ','ZYDUS WELL  ','ZYDUSLIFE   ', 'IOL CHEM PH ','ION EXCHANGE','IPCA LAB LTD',]
avoid_stocks = ['AURUMPP','AIRTELPP','182D290922','426GS2023','619GS2034','667GS2050','676GS2061','699GS2051','719GS2060',
                '769GS2043','772GS2055','795GS2032','817GS2044','AXISNIFTY','AXISBNKETF',
                'AXISBPSETF','AXISCETF','AXISHCETF','AXISTECETF','BBETF0432','DSPN50ETF',
                'DSPNEWETF','DSPQ50ETF','EBBETF0425','EBBETF0430','EBBETF0431','IBMFNIFTY','ICICI500','ICICIALPLV',
                'ICICAUTO', 'ICICIB22','ICICIBANKN','ICICIBANKP','ICICILIQ','ICICILOVOL','ICICIM150','ICICIMCAP','ICICINF100',
                'ICICINIFTY','ICICINV20','ICICINXT50','ICICIPHARM','ICICISENSX','ICICITECH','IDFNIFTYET',
                'KOTAKBKETF','KOTAKGOLD','KOTAKMID50','KOTAKNIFTY','KOTAKNV20','KOTAKPSUBK','LICNETFGSC','LICNETFN50',
                'LICNETFSEN','LICNFNHGP','LIQUIDETF','M17RG','MAESGETF','MAFSETF','MAMFGETF','MAN50ETF','MANXT50','MASPTOP50',
                'MOM100','MOM50','MON100','MONQ50','NCPSESDL24','NETFAUTO','NETFCONSUM','NETFDIVOPP','NETFGILT5Y','NETFIT',
                'NETFLTGILT','NETFMID150','NETFNIF100','NETFNV20','NETFPHARMA','NETFSDL26','NETFSILVER','NHBTF2014','NHBTF2023',
                'QGOLDHALF','QNIFTY','SBIETFCON','SBIETFIT','','SBIETFPB','SBIETFQLTY','SETF10GILT','SETFGOLD','SETFNIF50',
                'SETFNIFBK','SETFNN50','SETUINFRA','SGBAPR28I','SGBAUG24','SGBAUG27','SGBAUG28V','SGBAUG29V','SGBD29VIII',
                'SGBDC27VII','SGBFEB24','SGBFEB27','SGBFEB28IX','SGBFEB29XI','SGBJ28VIII','SGBJAN26','SGBJAN27','SGBJAN29IX',
                'SGBJAN29X','SGBJAN30IX','SGBJU29III','SGBJUL25','SGBJUL27','SGBJUL28IV','SGBJUL29IV','SGBJUN27','SGBJUN28',
                'SGBJUN29II','SGBMAR24','SGBMAR25','SGBMAR28X','SGBMAY25','SGBMAY26','SGBMAY28','SGBMAY29I','SGBMR29XII',
                'SGBN28VIII','SGBNOV23','SGBNOV24','SGBNOV25','SGBNOV25IX','SGBNOV25VI','SGBNV29VII','SGBOC28VII','SGBOCT25',
                'SGBOCT25IV','SGBOCT25V','SGBOCT26','SGBOCT27','SGBOCT27VI','SGBSEP24','SGBSEP27','SGBSEP28VI','SGBSEP29VI',
                'UTIBANKETF','UTINEXT50','UTINIFTETF','UTISENSETF','UTISXN50', 'KOTAKGOLDETF', 'SBI GOLD ETS',
                'QUANTUM GOLD', 'UTI GOLD ETF', 'JUNIORBEES  ', 'KOTAK PSU BK',
                'SHARIABEES  ', 'QNIFTY      ', 'HNGSNGBEES  ', 'MOM50       ', 'KOTAKBKETF  ', 'SETFNIFBK   ', 'SETFNIF50   ',
                'SGB2016I    ', 'SGB2016II   ', 'SGBAUG24    ', 'SGB2016IIA  ', 'SGB2016IIIA ', 'SGB2016IV   ', 'SGBMAY25    ',
                'SGBJULY25   ', 'SGBOCT25A   ', 'SGBNOV25A   ', 'SGBDEC25    ', 'SGBDEC25A   ', 'SGBDEC25B   ', 'SGBOCT26    ',
                'SGBJULY27   ', 'SGBAUG27    ', 'SGBDEC27    ', '716GOI2050  ', 'SGBAPR28    ', 'SGBMAY28    ', 'SGBJULY28   ',
                'SGBAUG28    ', 'SGBSEP28    ', 'SGBOCT28    ', 'SGBNOV28    ', 'SGBJAN29    ', 'SGBJAN29A   ', 'SGBFEB29    ',
                'SGBMAR29    ', 'SGBMAY29    ', 'SGBJUNE29   ', 'SGBJUN29A   ', 'SGBJULY29   ', 'SGBAUG29    ', 'SGBSEP29    ',
                'SGBNOV29    ', '699GOI2051  ', '695GOI2061  ', 'SGBDEC29    ', 'SGBJAN30    ', '735KARSDL40 ', '709APSDL39  ',
                '704APSDL34  ', '693KARSDL32 ', '689GUJSDL31 ', '601RAJSDL26 ', '990IFCI24F  ', '849NTPC25   ', '735PFC35    ',
                '753IRFC30   ', '76NHAI31    ', '749IREDA31  ', '753IREDA26  ', '774IREDA31  ', '768IREDA36  ', '727HUDCO26  ',
                '764HUDCO31  ', '769NHAI31   ', '729HUDCO26  ', '764NABARD31 ', '0MFL23A5    ', '88MMFSL23   ', '10EHFL26    ',
                '900MFL22A   ', '805MMFSL32  ', '9SEFL23B    ', '0SEFL23A    ', '888ERFL28   ', '925ERFL28   ', '0MFL23      ',
                '935SEFL23   ', '0SEFL23     ', '92SEFL28    ', '911JMFCSL23 ', '975JMFCSL28 ', '893STFCL23  ', '903STFCL28  ',
                '93STFCL23   ', '925EFL23    ', '943EFL28    ', '985EFL28    ', '866ICCL23   ', '9ICCL23     ', '92ICCL28    ',
                '890TCFSL23  ', '910TCFSL28  ', '912STFCL23  ', '930STFCL28  ', '10MFL23     ', 'MFL29NOV18D ', '10JMFCSL22  ',
                '0JMFCSL22   ', '967JMFCSL23 ', '995EFL24    ', '1040EFL24   ', 'EFL4JAN19A  ', '1015EFL29   ', '905MMFSL22  ',
                '93MMFSL27   ', '95MMFSL29   ', '1005SEFL24  ', '0SEFL24A    ', '1025KFSRVII ', '1041KFSVIII ', '912STFCL24  ',
                '96IFL22A    ', '10IFL29     ', '975MFL24    ', '1090DLSL22  ', '1050DLSL24  ', '11DLSL24    ', '925LTFL24   ',
                '935LTFL29   ', '898LTFL29   ', '975MFL24A   ', '975MFL22B   ', '89LTFL22    ', '9LTFL24     ', '905LTFL27   ',
                '965SCUF22   ', '975SCUF24   ', '935SCUF24   ', '95MHIL22    ', '1050SEFL22  ', '1025SEFL24A ', '1004JMFPL24 ',
                '102EFL22    ', '0EFL22      ', '995EFL24A   ', '104EFL24    ', '995EFL29    ', '85TCFS24    ', '885TCFS29   ',
                '0IFL22A     ', '0JMFPL26    ', '975MFL23    ', '0MHFL22     ', '1025MHFL24  ', '0ECL23      ', '995ECL24    ',
                '104ECL24    ', '995ECL29    ', '1071KFL25   ', '865LTFL26   ', '95MFL23A    ', '975MFL24BB  ', '0MFL24BB    ',
                '84TCHF28    ', '0EFIL23     ', '1025EFIL25  ', '97JFPL23    ', '0JFPL23     ', '0JFPL25     ', '10KFL23A    ',
                '1025KFL27A  ', '885MFL23    ', '9MFL23B     ', '0MFL23D     ', 'MFLOV24     ', 'MFLOVI25    ', '935EFSL24   ',
                '0EFSL24     ', '939EFSL26   ', '953EFSL31   ', 'MFLII26     ', 'MFLIV26     ', 'MFLVI26     ', '48PFCL24    ',
                '7PFCL31     ', '683PFCL31   ', '697PFCL36   ', '715PFCL36   ', '0KFL23A     ', '825MFL23    ', '0MFL23E     ',
                '0MFL27B     ', '825MFL23A   ', '96IFL28     ', 'MFLVI31F    ', '910EFSL24   ', '930EFSL31   ', '0MMFL23A    ',
                '82IGT31     ', '825MFCL23A  ', '0MFCL23VI   ', 'BILNCD2021  ', '85PCHFL24   ', '875PCHFL26  ', '9PCHFL31A   ',
                '0IHFL28     ', '91EFSL24    ', '915EFSL26   ', 'EFS10SEP21  ', '875MMFL23   ', '10MMFL27    ', '820JMFPL26  ',
                '0IIFL23     ', '925IML22    ', '12IML26     ', '825MFL24    ', '1003UCL24   ', '875EFSL23   ', '875EFSL24A  ',
                '91EFSL24A   ', 'EFSL281221A ', '955EFSL26B  ', 'EFSL281221B ', '97EFSL31A   ', '85MMFL23    ', '820IHFL27   ',
                '843IHFL29   ', '866IHFL25   ', '8MFL24      ', '875MFL28    ', '9MFL30      ', 'ZCMFL24     ', '1015UPPCL27 ',
                '1015UPPCL28 ', 'RCL310718   ', '1025STFCL24 ', '1025STFL24  ', '1175SIBL29  ', 'EFIL261219A ', '1375SIBLPER ',
                '741PFCL30   ', '85BOBPERP   ', '774SBIPER   ', 'PFCBS4      ', '830NHAI27   ', 'HUDCO050327 ', '870LTFL22A  ',
                '870LTFL22B  ', '89SEFL17B   ', '793REC22    ', '738REC27TF  ', '719IIFCL23  ', '734IRFC2028 ', '708IIFCL33  ',
                '801REC23    ', '839HUDCO23  ', '879NHPC28   ', '879PFC28    ', '883HUDCO29  ', '866IIFCL24C ', '891IIFCL34  ',
                '875NHAI29   ', '880IREDA29  ', '861KPL24    ', '900KPL29    ', '888REC29    ', '880IIFCL29  ', 'HDFCW3      ',
                'MOLDTKWARR  ', 'IFCI010811D ', 'IFCI150212D ', 'IFCI310312A ', 'IFCI310312C ', '990IFCI27B  ', '990IFCI32C  ',
                '893PTCIF22A ', '675PCHFL31  ', '1050MSFL22  ', 'KOTAK SENSEX', 'BSE  INFRA  ', 'UTISXN50    ', 'ICICISENSX  ',
                'BSLNIFTY    ', 'DSPN50ETF   ', 'MONQ50      ', 'DSPNEWETF   ', 'ICICICONSU  ', 'MASPTOP50   ', 'AXISCETF    ',
                'AXISTECETF  ', 'AXISHETF    ', 'ICICIFMCG   ', 'MAFSETF     ', 'ICICIPHARM  ', 'MAESGETF    ',
                'ICICIBANKN', 'UTIBANKETF  ', 'ICICITECH   ', 'EBBETF0425  ', 'EBBETF0431  ', '07GPG       ', '09GPG       ', '08MPD       ',
                '08GPG       ', '10ARD       ', '10GPG       ', '11DPR       ', '11GPG       ', '11MPD       ', '11MPR       ', '11QPD       ',
                '11AGG       ', '11AMD       ', '11DPD       ', 'ICICIM150   ', 'MANXT50ETF  ', 'EBBETF0430  ', 'ABSLBANETF  ', 'ICICIBANKP  ',
                'ICICIBANKN  ', 'NETFSNX150  ', 'ABSLNN50ET  ', 'MAN50ETF    ', 'SETFSN50    ', 'ICICILIQ    ', 'IPRU3168    ', 'IPRU3169    ',
                'ICICINXT50  ', 'ICICI500    ', 'LIQUIDETF   ', 'AXISCBDPD   ', 'AXISCBGPG   ', 'ICICIB22    ', 'UTINEXT50   ', '7NR         ',
                'ICICILOVOL  ', 'IDFSENSEXE  ', 'ICICIMCAP   ', 'ICICINV20   ', 'UTISXN50', 'NCPSESDL24', 'MAMFGETF', 'NETFSILVER', 'LIQUIDETF',
                'UTISXN50', 'MAMFGETF', 'HBANKETF', 'NHBTF2014', 'HDFCMFGETF', '824GS2027', 'MAMFGETF', 'UTISXN50',
                'BSLGOLDETF', 'LIQUIDETF', 'IDBIGOLD', 'ICICINIFTY', 'ICICINF100', 'NETFNIF100  ', 'KOTAKNIFTY', 'CPSE ETF    ',
                'MAESGETF', 'NETFSDL26', 'NETFSENSEX  ', 'SETFBSE100  ', 'SETF10GILT', 'UTISENSETF', 'UTINIFTETF', 'LICNETFN50', 'LICNETFSEN',
                'HDFCNIFETF', 'SXETF       ', 'LICNFNHGP', 'UTISENSETF  ', 'UTINIFTETF  ', 'ICICIBANKP', 'ICICICONSU', 'ICICIFMCG',
                'ICICILIQ', 'ICICILOVOL', 'ICICIM150', 'ICICIMCAP', 'ICICINF100', 'ICICINIFTY', 'ICICINV20', 'ICICINXT50', 'ICICIPHARM', 'ICICI500',
                'ICICIALPLV', 'ICICIAUTO', 'ICICIB22', 'ICICISENSX', 'ICICISILVE', 'ICICITECH', 'KOTAKNIFTY  ', 'LICNETFN50  ', 'LICNETFSEN  ',
                'HDFCNIFETF  ', 'LICNFNHGP   ', 'NIESSPJ     ', 'NIESSPC     ', 'NIEHSPI     ', 'NIESSPE     ', 'NIEHSPD     ', 'NIEHSPE     ',
                'NIEHSPG     ', 'NIEHSPH     ', 'NIEHSPL     ', 'NIESSPL     ', 'NIESSPM     ', 'ABCRSPRG    ', 'ABCRSPDG    ', 'ABMTSPRG    ',
                '667GS2050', '676GS2061', '699GS2051', '737GS2023', '813GS2045', '824GS2027', 'ABSLBANETF', 'ABSLNN50ET', 'AXISBNKETF', 'AXISBPSETF',
                'AXISCETF', 'AXISHCETF', 'AXISNIFTY', 'AXISTECETF', 'BBETF0432', 'BSLGOLDETF', 'BSLNIFTY', 'BSLSENETFG', 'CPSEETF',
                'DSPN50ETF', 'DSPNEWETF', 'DSPQ50ETF', 'HDFCMFGETF', 'HDFCNIFETF', 'HDFCSENETF', 'IBMFNIFTY', 'IDBIGOLD', 'IDFNIFTYET', 'IVZINGOLD',
                'IVZINNIFTY', 'KOTAKBKETF', 'KOTAKGOLD', 'KOTAKMID50', 'KOTAKNIFTY', 'KOTAKNV20', 'KOTAKPSUBK', 'LICNETFGSC', 'LICNETFN50', 'LICNETFSEN',
                'LICNFNHGP', 'LIQUIDETF', 'MAESGETF', 'MAFSETF', 'MAMFGETF', 'MAN50ETF', 'MANXT50', 'MASPTOP50', 'MC1RG', 'MC2RD', 'MC2RG',
                'MOM100', 'MOM50', 'MON100', 'MONQ50', 'NCPSESDL24', 'NETF', 'NETFAUTO', 'NETFCONSUM', 'NETFDIVOPP', 'NETFGILT5Y', 'NETFIT', 'NETFLTGILT',
                'NETFMID150', 'NETFNIF100', 'NETFNV20', 'NETFPHARMA', 'NETFSDL26', 'NETFSILVER', 'QGOLDHALF', 'QNIFTY', 'SBIETFCON', 'SBIETFIT', 'SBIETFPB',
                'SBIETFQLTY', 'SETFNIF50', 'SETFNIFBK', 'SETFNN50', 'SETUINFRA', 'SGBAPR28I', 'SGBAUG24', 'SGBAUG27', 'SGBAUG28V', 'SGBAUG29V', 'SGBD29VIII',
                'SGBDC27VII', 'SGBDEC25', 'SGBDEC2513', 'SGBDEC25XI', 'SGBFEB24', 'SGBFEB27', 'SGBFEB28IX', 'SGBFEB29XI', 'SGBJ28VIII', 'SGBJAN26', 'SGBJAN27',
                'SGBJAN29IX', 'SGBJAN29X', 'SGBJAN30IX', 'SGBJU29III', 'SGBJUL25', 'SGBJUL27', 'SGBJUL28IV', 'SGBJUL29IV', 'SGBJUN27', 'SGBJUN28',
                'SGBJUN29II', 'SGBMAR24', 'SGBMAR25', 'SGBMAR28X', 'SGBMAY25', 'SGBMAY26', 'SGBMAY28', 'SGBMAY29I', 'SGBMR29XII', 'SGBN28VIII', 'SGBNOV23',
                'SGBNOV24', 'SGBNOV25', 'SGBNOV258', 'SGBNOV25VI', 'SGBNOV26', 'SGBNV29VII', 'SGBOC28VII', 'SGBOCT25', 'SGBOCT25IV', 'SGBOCT26', 'SGBOCT27',
                'SGBOCT27VI', 'SGBSEP24', 'SGBSEP27', 'SGBSEP28VI', 'SGBSEP29VI', 'UTIBANKETF', 'UTINEXT50', 'UTINIFTETF', 'UTISENSETF', 'UTISXN50', 'ESSEN-RE    ', 'SGBOCT25    ', 'SGBMAR28    ', 'SGBJUN28    ', '676GOI2061  ', '664GOI35    ', 'SGBMARCH30  ', '805GUJ2028  ', 'AIRTELPP    ', 'PATINTPP    ', 'WARDWIZPP   ', 'TILAKPP     ', 'PRISMXPP    ', 'ASMTECPP    ', '0IFCI24G    ', '760PFC35    ', '743REC35    ', '732IRFC25   ', '739NHAI31A  ', '764IRFC31   ', '729NABARD26 ', 'MMFSL26A    ', '0MFL25      ', '925SEFL22   ', '0SEFL27     ', '9MFL23      ', '94STFCL28   ', '0STFCL23    ', '0EFL23      ', '965EFL23    ', '925AHFL23   ', '970STFCL28  ', 'MFL29NOV18C ', '101JMFCSL23 ', '915MMFSL24  ', '1015MFL24   ', '0MFL26      ', '0DLSL24     ', '10MFL24     ', '975MHIL24   ', '0EFL24      ', '975MFL24AA  ', '10MFL24A    ', '10KFL22AA   ', '0KFL23AA    ', '922STF24    ', '0STF23      ', '102JMFPL22  ', '985SCUF24   ', '945SCUF24   ', 'BILNCD      ', '10MFL22A    ', '95MFL23     ', '975MFL24B   ', '0MFL23A     ', '0MFL27      ', '0MHFL26     ', '102ECL23    ', '0ECL24      ', '845LTFL22   ', '0LTFL22BB   ', '815LTFL22   ', '801TCH25    ', '875STFCL27  ', '885STFCL23  ', '0STFCL23A   ', '10EFIL23    ', '975MVAFL25  ', '115KLM23    ', '0MFL23C     ', 'MFLIII24    ', 'MFLV24      ', '10KFL24C    ', '85MFL24A    ', 'MFLI24A     ', 'MFLV26E     ', '955EFSL26   ', '0MMFL25B    ', '1025MMFL26A ', 'KLM30JUL21  ', 'EFSL10SEP21 ', '9MMFL23     ', '0KSFL23     ', '842IIFL26   ', 'MFL291021   ', '93EFSL31A   ', 'ZCMMFL27    ', '850MFL27    ', 'ZCMFL30     ', '850EHFL24   ', 'EHFL29422   ', '870EHFL25   ', '915EHFL27   ', '970EHFL32   ', '1015UCL24   ', '1040UCL25   ', '1049DLSL22  ', '872PFC22A   ', '872PFC22    ', '1015UPPCL26 ', 'ELLD2J801A  ', '945SBIPER   ', '855HDFC29   ', 'KFL17DEC20  ', '722REC22TF  ', '875IIFCL33  ', '843PFC23    ', '892PFC33    ', '866NTPC23   ', '901HUDCO34  ', '852NHAI24   ', '848IRFC24   ', '865IRFC29   ', '898HUDCO29  ', '762NTPC35F  ', 'IFCI010811B ', 'IFCI150212C ', 'UCL200721   ', '970UPC29    ', '970UPPC30   ', '97UPPCL26   ', '97UPPCL27   ', '970UPCL31   ', '970UPCL32   ', 'sgbdec26' ,
                '09AGG       ','0MFCL24VII  ','0MHFL24     ','0STFCL24    ','1013DLSL24  ','10KAFL24    ','10KFL22C    ','10KSFL25    ','687MAHSDL33 ',
                '736PFC25    ','750IRFC35   ','795LTFHL22A ','812REC27    ','83TCHF25    ','854PFC28    ','871REC28    ','875SBIPERA  ','876HUDCO24  ',
                '876HUDCO28  ','888IRFC29   ','8MMFL23     ','905EHFL25   ','915EFSL26A  ','915RHFL27B  ','91TMFLPERP  ','935AHFL28   ','95MMFL23    ','95STFCL24   ','96IHFL28    ',
                '975MFL29    ','975MHFL22   ','975MMFL26   ','98EFIL25    ','98EFIL30    ','98EFSL26    ','9IBHFL26B   ', '0KFL25D     ','0KFL25D     ', '0MFL23CC    ', '0MFL23VI    ','0MFL25D     ', '1015HLFL25  ', '1025JFCSL28 ', '10KFIL27    ','1170IOB28   ','703HUDCO23  ','715NTPC25   ','735NHAI31   ','754NHAI30   ','775MFL23    ','830PFC2027  ','845TCFS22   ','846REC28    ','848IIFCL29A ',
                '850SBIPER   ','86LTFL24    ','875MFL23    ','875MFL26A   ','87BOBPER    ','915SEFL17B  ','925KFL24    ','93SCUF22    ','95MFL25     ','96STF24     ','975HLFL26A  ','975UPPCL25  ','990IFCI37D  ','9MFL27      ','9STFCL25    ',
                '08GPG       ','08MPD       ','11AGG       ','11AMD       ','11DPD       ','11DPR       ','11GPG       ','11MPD       ','11MPR       ','11QPD       ']

replace_index = {'Nifty 50':'NSENIFTY',
                 'Nifty 100':'NSE100' ,
                 'Nifty 200':'NIFTY200',
                 'Nifty 500':'NSE500',
                 'Nifty Midcap 50':'NIFTYMIDCAP50', #'MIDCAP50'
                 'Nifty Midcap 150':'NSEMIDCAP150',
                 'NIFTY Smallcap 100':'NSESMLCAP100',
                 'Nifty Midcap Liquid 15':'NIFTYMIDCAPLIQ15',
                 'NIFTY Midcap 100':'NSEMIDCAP',
                 'Nifty Auto' : 'NIFTYAUTO',
                 'Nifty Bank':'BANKNIFTY',
                 'Nifty Energy':'NIFTYENERGY',
                 'Nifty Financial Services':'NIFTYFINSERVICE',
                 'Nifty FMCG':'NIFTYFMGC',
                 'Nifty IT':'NSEIT',
                 'Nifty Media':'NIFTYMEDIA',
                 'Nifty Metal':'NIFTYMETAL',
                 'Nifty MNC':'NIFTYMNC',
                 'Nifty Pharma':'NIFTYPHARMA',
                 'Nifty PSU Bank':'NIFTYPSUBANK',
                 'Nifty Realty':'NIFTYREALTY',
                 'Nifty India Consumption':'NIFTYCONSUMPTION',
                 'Nifty Commodities':'NIFTYCOMMODITIES',
                 'Nifty Infrastructure':'NIFTYINFRA',
                 'Nifty PSE':'NIFTYPSE',
                 'Nifty Services Sector':'NIFTYSERVSECTOR',
                 'Nifty CPSE':'NIFTYCPSE',
                 'Nifty Smallcap 50':'NIFTYSMALLCAP50',
                 'Nifty Smallcap 250':'NIFTYSMALLCAP250',
                 'Nifty Private Bank':'NIFTYPVTBANK',
                 'India VIX' : 'INDIAVIX'
                 #'Nifty Consumer Durables':'',
                 }

'''

'''
