[theme]
# Primary accent color for interactive elements.
primaryColor = #6C8594"

# Background color for the main content area.
backgroundColor = "#777C7F" #"darkgrey" #"#062A4C"   #"#00172B"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "grey" #"#144573"   #"#0083B8"

# Color used for almost all text.
textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
#font = "Copper Black"
font = "monospace"
